# Generated by Django 6.0 on 2025-05-11 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DumbCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('based_in_eu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day_preferences', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('assigned', models.DateField()),
                ('completed', models.DateField()),
                ('estimated_time', models.DurationField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('scalar', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'expressions_ExPeRiMeNt',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Experiment_thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JSONFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
            ],
            options={
                'required_db_features': {'supports_json_field'},
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.BigIntegerField(db_column='the_integer')),
                ('float', models.FloatField(db_column='the_float', null=True)),
                ('decimal_value', models.DecimalField(decimal_places=17, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_awards', models.IntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UUIDPK',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rating', models.FloatField(null=True)),
                ('friends', models.ManyToManyField(blank=True, to='app.author')),
            ],
        ),
        migrations.CreateModel(
            name='NamedCategory',
            fields=[
                ('dumbcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.dumbcategory')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=('app.dumbcategory',),
        ),
        migrations.CreateModel(
            name='ProxyCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.dumbcategory',),
        ),
        migrations.CreateModel(
            name='RemoteEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.employee')),
                ('adjusted_salary', models.IntegerField()),
            ],
            bases=('app.employee',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_employees', models.PositiveIntegerField()),
                ('num_chairs', models.PositiveIntegerField()),
                ('based_in_eu', models.BooleanField(default=False)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ceo_set', to='app.employee')),
                ('point_of_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_point_of_contact_set', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manager'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('rating', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pubdate', models.DateField()),
                ('authors', models.ManyToManyField(to='app.author')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_contact_set', to='app.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.DateTimeField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_opening', models.DateTimeField()),
                ('friday_night_closing', models.TimeField()),
                ('books', models.ManyToManyField(to='app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.tag')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.namedcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('misc', models.CharField(max_length=25)),
                ('negate', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag')),
            ],
            options={
                'ordering': ['note'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midpoint', models.TimeField()),
                ('end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.time')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.time')),
            ],
        ),
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(null=True)),
                ('uuid_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uuidpk')),
            ],
        ),
    ]
