# Generated by Django 6.0 on 2025-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='goes_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
