# Generated by Django 6.0 on 2025-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_alias_author_goes_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
