# Generated by Django 6.0 on 2025-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DurationField()),
            ],
        ),
    ]
