# Generated by Django 6.0 on 2025-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_durationfieldmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFieldThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=100)),
                ('f', models.FileField(upload_to='')),
            ],
        ),
    ]
