# Generated by Django 6.0 on 2025-05-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_manufacturer_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=255)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies_given', to='app.manufacturer2')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies_received', to='app.manufacturer2')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer2',
            name='b',
            field=models.ManyToManyField(related_name='suppliers', through='app.Supply', to='app.manufacturer2'),
        ),
    ]
